# Generated by Django 4.2.6 on 2023-11-14 00:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pollpal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
