# Generated by Django 4.2.6 on 2023-11-09 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pollpal', '0002_alter_customuser_options_alter_customuser_managers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_staff',
        ),
    ]
