# Generated by Django 4.2.6 on 2023-10-14 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pollpal', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='date',
            name='times_id',
        ),
        migrations.AddField(
            model_name='date',
            name='times',
            field=models.ManyToManyField(to='pollpal.time'),
        ),
    ]
